Kas73/SOEN-341-Project

README.md
Updated branch teamInfo with my name and username.
Regarding Issue #1
=> Added name Kasra Kamjoo to teamInfo

README.md
=> Added my name to the README file, #1

README.md
Added name & username. Issue #1
=> Adding my info to README, #1

README.md
hello team, i added my information to the readme
=> added my real name and username to README.md

README.md
Added name and username for Mitchel Scott-Bond. Issue #1
=> Added my name to readme file #1

README.md
As stated in title, this is an update to the README so that it has my name in it.
=> Update README.md with Gabriel Brodeur name

.gitignore, package.json
Added cors, dotenv, express, mongodb, mongoose and react-router-dom dependencies to package.json.
Also updated the test script to server instead, which runs the server using node. Added .gitignore that will ignore installed modules and vscode settings #30
=> Added dependencies to package.json and added .gitignore

public/index.html, src/App.css, src/App.js, src/components/AddNewProduct.jsx, src/components/Home.jsx, src/components/Login.jsx, src/components/layout/Footer.jsx, src/components/layout/Navbar.jsx, src/index.js
Created the Navbar and Footer page and added the Login and AddNewProducts and Home page,
front-end only
=> Added Login and AddNewProduct pages #32 #33

src/App.js, src/components/SignUp.jsx
Added the Sign-Up page. 
This includes first name, last name, email, password, and a create account button.   
#38
=> Adding front-end for sign-up page

client/src/components/AddNewProduct.jsx
Changed the button on the create-product form to be of type button instead of submit. Apparently having a button of type submit causes issues with the post request to the server.
#37
=> Fixing Broken Create POST request

client/src/App.css, client/src/components/SignUp.jsx
Centered all the text items of the create account page to match the login page. #51
=> Edited the layout of Create account page.

client/src/App.js, client/src/components/Home.jsx, client/src/components/Login.jsx, client/src/components/SignUp.jsx
Issues #54 and #55 
Because there was a project restructuring when implementing the database, the way we display these pages is different from how it used to be. As such, the two pages have been updated to extend React.Component.
=> Refactor login and signup Front-End Only

client/package-lock.json, client/src/components/Login.jsx, client/src/components/SignUp.jsx, models/users.model.js, package-lock.json, routes/users.routes.js, server.js
Added the Schema and route for Users database.
Refactored SignUp page. to add new user to the database.
Refactored user authentication on the Login page.
=> Added Schema, route for Users DB, refactored SignUp and Login page #58

client/src/components/layout/Navbar.jsx
i added a link to /create-product; which allows admin users to add a product to DB
#49 #17
=> added add product link for admin users to navbar jsx

client/src/App.js, client/src/components/Checkout.jsx
Deleted the Promo Code block of the checkout page since that will not be an option for our site. Added checkout page to routes so that it can be accessed through a url #60
For now, it is using Dummy data, but once all the database hooks are created, it will need to be updated to dynamically populate.
=> Refactored HTML of checkout page so that it is now a React Component

client/package-lock.json, client/package.json, client/src/components/Home.jsx, client/src/components/Login.jsx, client/src/components/SignUp.jsx, client/src/components/layout/Navbar.jsx, client/src/index.js
Included a new dependency 'react-cookie' which will allow persistency for logging in. Modified the home page to be a functional react component instead of a class (functionality is the same). Modified the login page so that it generates a cookie for the user when they successfully log in. Modified the sign up page so that the user is logged in once they have successfully created an account. Both the login and signup will redirect the user to the home page if they are already logged in. Modified the navbar so that it shows who you are logged in as, and hides the login/signup options if you are already logged in. The add product page is now hidden on the navbar when a user is not logged in #70
=> Cookies for user login

client/src/components/AddNewProduct.jsx, client/src/components/Checkout.jsx, client/src/components/Login.jsx, client/src/components/SignUp.jsx
#74 and #76
Refactor two pages so that they are functional react components instead of extending the react class
Fixed issue with axios requests 404ing
=> Refactor AddNewProducts and Checkout Page to no longer extend React.Component and fixed login/signup bug

client/package-lock.json, client/src/App.css, client/src/App.js, client/src/components/Cart.jsx, client/src/components/CartRow.jsx, client/src/components/layout/Navbar.jsx, models/carts.model.js, routes/carts.routes.js, server.js
Added the React component for the Cart page, Added link to Cart page in the Navbar, Added the model and routes for Cart database
=> Add cart frontend and backend #75 

client/package-lock.json, client/src/App.css, client/src/components/ProductList.jsx, package-lock.json
placeholder for images is product.name for now until db is setup for product images
#17 #79 
I also edited the css with new classes relevant to the grid-container
had some merge conflicts that needed to be resolved because branch was not up to date with main before changes were made (see commits)
=> added a grid to ProductList with linked names and images

client/src/components/AddNewProduct.jsx, client/src/components/ProductList.jsx, models/products.model.js, routes/products.routes.js, server.js
Modified the product model to exclude the quantity_in_stock, but now includes the a seller_name, description and an image which is converted to base64. Refactored the post route for products to include the changes to model. Modified the server.js because there is an arbitrary limit of 1mb when making requests, which has now been increased to 6mb in order to fit the image as base64 (image has 5mb limit), modified the product list so that it displays the img for each item. Modified add new products to have a description field (previously quantity) and added an input for uploading an image for the product. When a valid image is uploaded, it is displayed on screen. #83
=> Refactored products model and routes/pages to match the new model.

client/src/App.js, client/src/components/DetailsPage.jsx, client/src/components/ProductList.jsx, routes/products.routes.js
Added product details page that queries the database and displays information for a single product. Added route to our product routes to be able to search for a single item. Added Route to App.js to include the details page route. Modified productList so that when you click on an item in the grid, it will redirect to that products detail page #62
Done with the help of @mitchelscottbond
=> Product Details page that dynamically populates

client/src/components/layout/Navbar.jsx
Modified Navbar so that when the user clicks Logout it redirects them to the home page #86
=> Logout redirects to Home page

client/src/components/DetailsPage.jsx, routes/carts.routes.js
When clicked, creates a cart if the user doesn't have one, or updates the cart. When updating, if a product existing in the cart already is added, increases the quantity in cart. If the item doesn't exist, adds it to cart array. Updated carts routes to have an 'update' route for the cart. #88
A quantity is now included on the details page, you can increment, decrement or type the quantity you desire. This was added for the purposes of the cart.
=> Implemented the Add to cart button.

client/src/components/Cart.jsx, client/src/components/CartRow.jsx
Involved tasks: #90, #91 and #92
Changed the front end to pull the cart information for a user from the database.
Implemented the remove an item button on the cart page
Implemented the ability to increment and decrement the quantity of a single item in your cart.
=> Implementing basic cart page functionalities

models/users.model.js, routes/users.routes.js
Added payments method object to the users model
Added payments method object to the users route
=> Added payments method object to users database, issue #97

client/src/App.css, client/src/App.js, client/src/components/SearchResults.jsx, client/src/components/layout/Navbar.jsx, routes/products.routes.js
This commit includes the webpage that displays when you search for a product. The backend logic that displays that product, and entering data into the search bar.
=> Search for a product results page #25

client/src/components/Cart.jsx
Added a check in the decrement function that stops the quantity from going below 1
=> User can no longer set quantities below 1 on cart page #95

client/src/components/DetailsPage.jsx
Fix the look of the increment and decrement quantity buttons on the product details page
- added bootstrap classes to the btns
=> Fix the look of the increment and decrement quantity buttons on the product details page #94

client/src/App.css, client/src/components/Checkout.jsx, client/src/components/CheckoutListRow.jsx
Fixed the look of the cart on the checkout page. Added the functionality for showing the total sum owed.
=> Fixed the look of the cart on the checkout page. Display the bill. #66

client/src/components/DetailsPage.jsx
Also disabled the user's ability to type in the input box so that they cannot put letters in the quantity box #117
=> Changed decrement function for quantity so that it cannot go below 0

models/reviews.model.js, routes/reviews.routes.js, server.js
Review models and routes added to meet requirements of user story: #71.
=> review model and routes added

client/src/App.css, client/src/App.js, client/src/components/Checkout.jsx, client/src/components/OrderHistory.jsx, client/src/components/OrderList.jsx, client/src/components/OrderProductList.jsx, client/src/components/layout/Navbar.jsx, models/orders.model.js, routes/orders.routes.js
This includes a fully functioning order history page as dictated in epic user story #19. 
Listing all orders for a user is successful.
Canceling an order removes an order from the database. 
This concludes #107
=> Order history page #107

client/src/components/OrderSuccessful.jsx
Added links to order-history page and ratings page
Added order successful message
=> Fix order successful page #132

client/src/components/Login.jsx, client/tests/data/dummyUser.data.json, client/tests/login.test.js
A basic check that the elements are rendered and that the user can input values. #128
=> Implemented some unit tests for the login page

client/src/components/OrderList.jsx, client/src/components/OrderProductList.jsx, client/tests/data/dummyOrder.data.json, client/tests/orderList.test.js
Added one test that checks that the id, total, inner product list and cancel button exist. Added a test that checks that every product in the inner product list has a price, the product name and quantity.
=> Added basic unit tests for OrderList object #136 

client/src/components/Checkout.jsx
Change redirect to order-successful page to use the useNavigate hook after an order is submitted, rather than an a tag #138
=> Fix bug where order is not processed when clicking place order
